databaseChangeLog:
  - changeSet:
      id: 0009-1-insert-vertikal-configuration-prices
      author: furniture-calculator
      changes:
        - sql:
            sql: >-
              INSERT INTO configuration_price (retail_price, dealer_price, leaf_type_id)
              SELECT 29952, 18720, id FROM leaf_type
              WHERE code IN ('LT-001', 'LT-002', 'LT-003', 'LT-004', 'LT-005', 'LT-006', 'LT-007')
