databaseChangeLog:
  - changeSet:
      id: 0056-1-add-fantom-reverse-configurations
      author: furniture-calculator
      changes:
        - sql:
            sql: >-
              INSERT INTO door_configuration (leaf_type_id, frame_type_id, edge_type_id, door_casing_type_id, frame_extensions_type_id, is_reverse)
              SELECT dc.leaf_type_id, dc.frame_type_id, dc.edge_type_id, dc.door_casing_type_id, dc.frame_extensions_type_id, true
              FROM door_configuration dc
              JOIN frame_type ft ON ft.id = dc.frame_type_id
              WHERE ft.code = 'FT-001' AND dc.is_reverse = false
