databaseChangeLog:
  - changeSet:
      id: 0067-1-dobor-ts-configuration-price-length-decouple
      author: furniture-calculator
      changes:
        - sql:
            sql: >-
              UPDATE configuration_price
              SET length_option_id = NULL
              WHERE frame_extensions_type_id IN (
                SELECT id FROM frame_extensions_type WHERE code IN ('FET-004', 'FET-005', 'FET-006', 'FET-007')
              )
