spring:
  application:
    name: FurnitureCalculator
  datasource:
    url: jdbc:postgresql://localhost:5432/furniture_calculator
    username: furniture_calculator
    password: furniture_calculator
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
